language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt coverageReport
  - sbt coverageAggregate
  - pip install codecov && codecov --token=${CODECOV_KEY}
