language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

install:
  - pip install codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt coverageReport
  - sbt coverageAggregate
  - codecov --token=${CODECOV_KEY}
